import type { NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: bakeries } = trpc.useQuery(["bakery.getAll"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4 space-x-4 space-y-4">
        {bakeries?.map(({ id, name, info, address }) => (
          <Card key={id} name={name} info={info} address={address} />
        ))}
      </main>
    </>
  );
};

const Card = ({ name = "", address = "", info = "" }) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{info}</p>
      <p className="text-sm text-gray-600">{address}</p>
    </section>
  );
};

export default Home;
